config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  get 'welcome/index'

  resources :restaurants
  resources :articles

  root 'welcome#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, presence: true
#	validates :description, presence: true
#	validates :address, presence: true
#	validates :phone_number, presence: true,
#					 length: { minimum: 7 }				 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def new
	
end

def create

end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
def index
	@restaurants = Restaurant.all
end
	
def show
	@restaurant = Restaurant.find(params[:id])
end

def new
	@restaurant = Restaurant.new
end

def edit
	@restaurant = Restaurant.find(params[:id])
end
def create
	@restaurant = Restaurant.new(restaurant_params)

	if @restaurant.save
		redirect_to @restaurant
	else
		render 'new'
	end
	#render plain: params[:restaurant].inspect
end
def update
	@restaurant = Restaurant.find(params[:id])

	if @restaurant.update(restaurant_params)
		redirect_to @restaurant
	else
		render 'edit'
	end
end
def destroy
	@restaurant = Restaurant.find(params[:id])
	@restaurant.destroy

	redirect_to restaurants_path
end
private
	def restaurant_params
		params.require(:restaurant).permit(:name, :description, :address, :phone_number)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit a Restaurant's details</h1>
 
<%= form_for :restaurant, url: restaurant_path(@restaurant), method: :patch do |f| %>
 
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@restaurant.errors.count, "error") %> prohibited
        this restaurant from being saved:
      </h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

   <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>List of Restaurants</h1>
<%= link_to "Add Restaurant", new_restaurant_path %>
<table>
	<tr>
		<th>Name</th>
		<th>Desription</th>
		<th>Address</th>
		<th>Phone_number</th>
		<th colspan = '3'> </th>
	</tr>

	<% @restaurants.each do |restaurant| %>
		<tr>
			<td><%= restaurant.name %></td>
			<td><%= restaurant.description %></td>
			<td><%= restaurant.address %></td>
			<td><%= restaurant.phone_number %></td>
			<td><%= link_to 'Show', restaurant_path(restaurant) %></td>
			<td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
			<td><%= link_to 'Destroy', restaurant_path(restaurant),
					method: :delete,
					data: { confirm: 'are you sure?'} %></td>
		</tr>
	<% end %>


</table>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>
<%= form_for :restaurant, url: restaurants_path do |f| %>


	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name%>
	</p>
	<p>
		<%= f.label :description%><br>
		<%= f.text_area :description%>
	</p>
	<p>
		<%= f.label :address%><br>
		<%= f.text_area :address%>
	</p>
	<p>
		<%= f.label :phone_number%><br>
		<%= f.text_field :phone_number%>
	</p>
	<p>
		<%= f.submit%>
	</p>
<% end %>

<%= link_to "Back", restaurants_path %>

app/views/restaurants/show.html.erb
<p>
	<strong>Name</strong>
	<%= @restaurant.name %>
</p>

<p>
	<strong>Description</strong>
	<%= @restaurant.description %>
</p>

<p>
	<strong>Address</strong>
	<%= @restaurant.address %>
</p>

<p>
	<strong>Phone_number</strong>
	<%= @restaurant.phone_number %>
</p>

<%= link_to "Edit", edit_restaurant_path(@restaurant) %> |
<%= link_to "Back", restaurants_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>